//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace БИПиТ9
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int IdO { get; set; }
        public int IdC_FK { get; set; }
        public int IdS_FK { get; set; }
        public int Time { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Service Service { get; set; }
    }
}
